app:
    # The max number of goroutines that run on parallel to process
    # the rides dataset. Increasing this value will process a dataset fast
    # but a very big value will cause error due to maximum number of concurrent operations has reached
    max_goroutines: 100

segment:
    # Segment considered invalid if the speed is more than this value
    # the value is in km/h
    max_speed_threshold: 100

    pricing:
        idle:
            min_threshold: 10
            # The price per hour
            price_per_hour: 11.90

        moving:
            # Time of day (05:00, 00:00) per km
            from_05_00_per_km: 0.74

            # Time of day (00:00, 05:00) per km
            from_00_05_per_km: 1.30

fare:
    standard_fee: 1.30
    minimum:  3.47
